<?php
/**
 * Created by PhpStorm.
 * User: szrh
 * Date: 2019/4/18
 * Time: 9:57
 */
namespace app\index\controller;

use think\Controller;

class Camera extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->view->replace([
            '__PUBLIC__'    =>  '/thinkphp/public',
        ]);
    }


}