<?php
/**
 * Created by PhpStorm.
 * User: szrh
 * Date: 2019/4/15
 * Time: 15:42
 */
namespace app\index\controller;

use app\index\model\SubwayCamera as SubwayCameraModel;
use app\index\model\MonitorMeters as MonitorMetersModel;
use app\index\model\SubwayStation as SubwayStationModel;
use think\Controller;

class DeviceManage extends Controller
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->view->replace([
            '__PUBLIC__'    =>  '/thinkphp/public',
        ]);

        $user_id = session('uid');

        if(empty($user_id))
        {
            $this->view->engine->layout(false);

            $this->error("请登录", '../index');
        }
    }

    /**
     * 地铁摄像头分布图
     *
     * @return mixed
     */
    public function subway_camera()
    {
        $this->assign('left_menu','subway_camera');

        return $this->fetch();
    }

    /**
     * 显示车站摄像头分布图
     *
     * @return mixed
     */
    public function station_camera()
    {
        $camera_list = SubwayCameraModel::all();

        $this->assign('camera_list', $camera_list);
        $this->assign('left_menu', 'subway_camera');
        return $this->fetch();
    }

    /**
     * 监控室摄像头列表
     *
     * @return mixed
     */
    public function camera_room()
    {
        return $this->fetch();
    }

    /**
     * 摄像头控制
     *
     * @return mixed
     */
    public function camera_control()
    {
        return $this->fetch();
    }

    public function meter_set()
    {
        return $this->fetch();
    }

    /**
     * 摄像头列表
     *
     * @return mixed
     */
    public function camera_list()
    {
        $camera_list = SubwayCameraModel::all();

        $this->assign('camera_list', $camera_list);
        $this->assign('left_menu', 'camera_list');
        return $this->fetch();
    }

    /**
     * 添加新摄像头
     * @return mixed
     */
    public function add_camera()
    {
        $station_list = SubwayStationModel::all();

        $this->assign('station_list', $station_list);
        $this->assign('left_menu', 'camera_list');
        return $this->fetch();
    }

    /**
     * 保存新摄像头信息
     */
    public function do_add_camera()
    {
        $data['name'] = $_POST['name'];
        $data['serial_number']  =   $_POST['serial_number'];
        $data['subway_station_id']     =   $_POST['subway_station_id'];

        $data['ip'] =   $_POST['ip'];
        $data['description']    =   $_POST['description'];

        SubwayCameraModel::create($data);
        $this->redirect('deviceManage/camera_list');
    }

    /**
     * 修改摄像头信息
     *
     * @param $id
     * @return mixed
     * @throws \think\exception\DbException
     */
    public function edit_camera($id)
    {
        $camera_info = SubwayCameraModel::get($id);
        $station_list = SubwayStationModel::all();

        $this->assign('station_list', $station_list);
        $this->assign('camera_info', $camera_info);
        $this->assign('left_menu', 'camera_list');
        return $this->fetch();
    }

    /**
     * 保存修改的信息
     *
     * @param $id
     */
    public function do_edit_camera($id)
    {
        $data['name']   =   $_POST['name'];
        $data['serial_number']  =   $_POST['serial_number'];

        $data['subway_station_id'] =   $_POST['subway_station_id'];
        $data['ip'] =   $_POST['ip'];
        $data['description']    =   $_POST['description'];

        SubwayCameraModel::update($data, array('id' => $id));
        $this->redirect('deviceManage/camera_list');
    }

    /**
     * 删除摄像头
     *
     * @param $id
     * @throws \think\exception\DbException
     */
    public function delete_camera($id)
    {
        $camera_info = SubwayCameraModel::get($id);
        if($camera_info)
        {
            $camera_info->delete();
            $this->redirect('deviceManage/camera_list');
        }
        else
        {
            $this->redirect('deviceManage/camera_list');
        }
    }

    /**
     * 仪表列表
     *
     * @return mixed
     */
    public function meter_list()
    {
        $meters = MonitorMetersModel::all();

        $this->assign('meter_list', $meters);
        $this->assign('left_menu', 'meter_list');
        return $this->fetch();
    }

    /**
     * 增加新仪表
     *
     * @return mixed
     */
    public function add_meter()
    {
        $station_list = SubwayStationModel::all();

        $this->assign('station_list', $station_list);
        $this->assign('left_menu', 'meter_list');
        return $this->fetch();
    }

    /**
     * 保存新仪表信息
     */
    public function do_add_meter()
    {
        $data['name']   =   $_POST['name'];
        $data['type']   =   $_POST['type'];
//        $data['subway_monitor_room_id'] =   $_POST['subway_monitor_room_id'];
        $data['subway_station_id'] =   $_POST['subway_station_id'];
        $data['max_normal'] =   $_POST['max_normal'];
        $data['min_normal'] =   $_POST['min_normal'];
        $data['description']    =   $_POST['description'];

        $base64_image_content = $_POST['recg_image'];
        //将base64编码转换为图片保存
        if (preg_match('/^(data:\s*image\/(\w+);base64,)/', $base64_image_content, $result)) {
            $type = $result[2];

            $new_file = "../public/uploads/";
            if (!file_exists($new_file)) {
                //检查是否有该文件夹，如果没有就创建，并给予最高权限
                mkdir($new_file);
            }

            $img = time() . ".{$type}";
            $new_file = $new_file . $img;

            //将图片保存到指定的位置
            if (file_put_contents($new_file, base64_decode(str_replace($result[1], '', $base64_image_content)))) {

                $data['recg_image'] = $new_file;
            }
        }

        MonitorMetersModel::create($data);
        $this->redirect('deviceManage/meter_list');
    }

    public function edit_meter($id)
    {
        $meter_info = MonitorMetersModel::get($id);

        $station_list = SubwayStationModel::all();

        $this->assign('station_list', $station_list);
        $this->assign('meter_info', $meter_info);
        $this->assign('left_menu', 'meter_list');
        return $this->fetch();
    }

    public function do_edit_meter($id)
    {
        $data['name']   =   $_POST['name'];
        $data['type']   =   $_POST['type'];
//        $data['subway_monitor_room_id'] =   $_POST['subway_monitor_room_id'];
        $data['subway_station_id'] =   $_POST['subway_station_id'];
        $data['max_normal'] =   $_POST['max_normal'];
        $data['min_normal'] =   $_POST['min_normal'];

        $data['description']    =   $_POST['description'];

        $base64_image_content = $_POST['recg_image'];
        //将base64编码转换为图片保存
        if (preg_match('/^(data:\s*image\/(\w+);base64,)/', $base64_image_content, $result)) {
            $type = $result[2];

            $new_file = "../public/uploads/";
            if (!file_exists($new_file)) {
                //检查是否有该文件夹，如果没有就创建，并给予最高权限
                mkdir($new_file);
            }

            $img = time() . ".{$type}";
            $new_file = $new_file . $img;

            //将图片保存到指定的位置
            if (file_put_contents($new_file, base64_decode(str_replace($result[1], '', $base64_image_content)))) {

                $data['recg_image'] = $new_file;
            }
        }

        MonitorMetersModel::update($data, array('id' => $id));
        $this->redirect('deviceManage/meter_list');
    }

    public function delete_meter($id)
    {
        $meter_info = MonitorMetersModel::get($id);
        if($meter_info)
        {
            $meter_info->delete();
            $this->redirect('deviceManage/meter_list');
        }
        else
        {
            $this->redirect('deviceManage/meter_list');
        }
    }
}