<?php
/**
 * Created by PhpStorm.
 * User: szrh
 * Date: 2019/4/15
 * Time: 15:42
 */
namespace app\index\controller;

use app\index\model\SubwayCamera as SubwayCameraModel;
use app\index\model\SubwayCamera;
use think\Controller;

class DeviceManage extends Controller
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->view->replace([
            '__PUBLIC__'    =>  '/thinkphp/public',
        ]);
    }

    /**
     * 地铁摄像头分布图
     *
     * @return mixed
     */
    public function subway_camera()
    {
        $this->assign('left_menu','subway_camera');

        return $this->fetch();
    }

    /**
     * 显示车站摄像头分布图
     *
     * @return mixed
     */
    public function station_camera()
    {
        return $this->fetch();
    }

    /**
     * 监控室摄像头列表
     *
     * @return mixed
     */
    public function camera_room()
    {
        return $this->fetch();
    }

    /**
     * 摄像头控制
     *
     * @return mixed
     */
    public function camera_control()
    {
        return $this->fetch();
    }

    public function meter_set()
    {
        return $this->fetch();
    }

    /**
     * 摄像头列表
     *
     * @return mixed
     */
    public function camera_list()
    {
        $camera_list = SubwayCameraModel::all();

        $this->assign('camera_list', $camera_list);
        $this->assign('left_menu', 'camera_list');
        return $this->fetch();
    }

    /**
     * 添加新摄像头
     * @return mixed
     */
    public function add_camera()
    {
        $this->assign('left_menu', 'camera_list');
        return $this->fetch();
    }

    /**
     * 保存新摄像头信息
     */
    public function do_add_camera()
    {
        $data['name'] = $_POST['name'];
        $data['serial_number']  =   $_POST['serial_number'];
        $data['station_id']     =   $_POST['station_id'];
        $data['subway_monitor_room_id'] =   $_POST['subway_monitor_room_id'];
        $data['ip'] =   $_POST['ip'];
        $data['description']    =   $_POST['description'];

        SubwayCameraModel::create($data);
        $this->redirect('deviceManage/camera_list');
    }

    /**
     * 修改摄像头信息
     *
     * @param $id
     * @return mixed
     * @throws \think\exception\DbException
     */
    public function edit_camera($id)
    {
        $camera_info = SubwayCameraModel::get($id);
        $this->assign('camera_info', $camera_info);
        $this->assign('left_menu', 'camera_list');
        return $this->fetch();
    }

    /**
     * 保存修改的信息
     *
     * @param $id
     */
    public function do_edit_camera($id)
    {
        $data['name']   =   $_POST['name'];
        $data['serial_number']  =   $_POST['serial_number'];
        $data['subway_monitor_room_id'] =   $_POST['subway_monitor_room_id'];
        $data['station_id'] =   $_POST['station_id'];
        $data['ip'] =   $_POST['ip'];
        $data['description']    =   $_POST['description'];

        SubwayCameraModel::update($data, array('id' => $id));
        $this->redirect('deviceManage/camera_list');
    }

    /**
     * 删除摄像头
     *
     * @param $id
     * @throws \think\exception\DbException
     */
    public function delete_camera($id)
    {
        $camera_info = SubwayCameraModel::get($id);
        if($camera_info)
        {
            $camera_info->delete();
            $this->redirect('deviceManage/camera_list');
        }
        else
        {
            $this->redirect('deviceManage/camera_list');
        }
    }
}