<?php
/**
 * Created by PhpStorm.
 * User: szrh
 * Date: 2019/4/17
 * Time: 17:56
 */
namespace app\index\controller;

use app\index\model\SubwayCompany as SubwayCompanyModel;
use app\index\model\SubwayLine as SubwayLineModel;
use app\index\model\SubwayLine;
use think\Controller;

class SubwayManage extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->view->replace([
            '__PUBLIC__'    =>  '/thinkphp/public',
        ]);
    }

    /**
     * 地铁运营公司列表
     *
     * @return mixed
     * @throws \think\exception\DbException
     */
    public function company_list()
    {
        $subway_company = SubwayCompanyModel::all();
        $this->assign('subway_company_list', $subway_company);
        return $this->fetch();
    }

    /**
     * 增加新公司
     *
     * @return mixed
     */
    public function add_company()
    {
        return $this->fetch();
    }

    /**
     * 保存新增公司信息
     */
    public function do_add_company()
    {
        $data['name'] = $_POST['name'];
        $data['description'] = $_POST['description'];

        SubwayCompanyModel::create($data);
        $this->redirect('subwayManage/company_list');
    }

    /**
     * 修改公司信息
     *
     * @param $id
     * @return mixed
     * @throws \think\exception\DbException
     */
    public function edit_company($id)
    {
        $company = SubwayCompanyModel::get($id);
        $this->assign('company', $company);
        return $this->fetch();
    }

    /**
     * 保存公司修改信息
     *
     * @param $id
     */
    public function do_edit_company($id)
    {
        $data['name'] = $_POST['name'];
        $data['description'] = $_POST['description'];

        SubwayCompanyModel::update($data, array('id' => $id));
        $this->redirect('subwayManage/company_list');
    }

    /**
     * 删除公司信息
     *
     * @param $id
     * @throws \think\exception\DbException
     */
    public function delete_company($id)
    {
        $company = SubwayCompanyModel::get($id);
        if($company)
        {
            $company->delete();
            $this->redirect('subwayManage/company_list');
        }
        else
        {
            $this->redirect('subwayManage/company_list');
        }
    }


    public function line_list()
    {

        $line_list = SubwayLineModel::all();
        $this->assign('line_list', $line_list);
        return $this->fetch();
    }

    /**
     * 新增地铁线路
     *
     * @return mixed
     */
    public function add_line()
    {
        return $this->fetch();
    }

    /**
     * 增加新线路
     */
    public function do_add_line()
    {
        $data['name'] = $_POST['name'];
        $data['subway_company_id']  = $_POST['subway_company_id'];
        $data['description']    = $_POST['description'];

        SubwayLineModel::create($data);
        $this->redirect('subwayManage/line_list');
    }

    /**
     * 编辑地铁线路信息
     *
     * @param $id
     * @throws \think\exception\DbException
     */
    public function edit_line($id)
    {
        $line_info = SubwayLineModel::get($id);
        $this->assign('line_info', $line_info);
        return $this->fetch();
    }

    public function do_edit_line($id)
    {
        $data['name'] = $_POST['name'];
        $data['subway_company_id']  = $_POST['subway_company_id'];
        $data['description'] = $_POST['description'];

        SubwayLineModel::update($data, array('id' => $id));
        $this->redirect('subwayManage/line_list');
    }

    public function delete_line($id)
    {
        $subway_line = SubwayLineModel::get($id);
        if($subway_line)
        {
            $subway_line->delete();
            $this->redirect('subwayManage/line_list');
        }
        else
        {
            // 不存在该线路
            $this->redirect('subwayManage/line_list');
        }
    }
}